import type { CMSState, Content } from "./types"

export const defaultContent: Content = {
  ar: {
    site: {
      name: "KYCtrust",
      description: "خدمة متخصصة في الحسابات البنكية الإلكترونية والخدمات المالية الآمنة",
      phone: "+20-106-245-3344",
      tagline: "شريكك الموثوق في العالم الرقمي",
      logoSrc: "/images/brand/novapay-logo.png",
    },
    hero: {
      title: "KYCtrust",
      subtitle: "منصة متكاملة للخدمات المالية الرقمية",
      description: "احصل على أفضل الحسابات البنكية الإلكترونية والمحافظ الرقمية بأمان وسرعة لا مثيل لها",
      cta: "ابدأ رحلتك المالية",
      secondary: "تصفح خدماتنا",
      stats: [
        { number: "1000+", label: "عميل راضي" },
        { number: "24/7", label: "دعم فني" },
        { number: "99.9%", label: "معدل النجاح" },
        { number: "15+", label: "خدمة متاحة" },
      ],
    },
    services: [
      {
        id: "paypal",
        name: "حساب PayPal",
        title: "حساب PayPal",
        price: "$15",
        category: "محافظ رقمية",
        icon: "💳",
        iconImage: "/images/logos/paypal.png",
        popular: true,
        active: true,
        sort: 1,
        description: "حساب PayPal مفعل بالكامل مع إمكانية الإرسال والاستقبال",
        note: "يتضمن تفعيل كامل",
        features: ["تفعيل كامل", "إرسال واستقبال", "دعم فني مجاني"],
      },
      {
        id: "payoneer",
        name: "حساب Payoneer",
        title: "حساب Payoneer",
        price: "$30",
        category: "حسابات مصرفية",
        icon: "💼",
        iconImage: "/images/logos/payoneer.png",
        popular: true,
        active: true,
        sort: 2,
        description: "حساب Payoneer مع بطاقة ماستركارد",
        note: "يشمل بطاقة فيزيائية",
        features: ["بطاقة ماستركارد", "تحويلات دولية", "سحب نقدي"],
      },
      {
        id: "wise",
        name: "حساب Wise",
        title: "حساب Wise",
        price: "$30",
        category: "تحويلات دولية",
        icon: "🌍",
        iconImage: "/images/logos/wise.png",
        popular: false,
        active: true,
        sort: 3,
        description: "حساب Wise للتحويلات الدولية بأقل الرسوم",
        note: "أفضل أسعار الصرف",
        features: ["أسعار صرف حقيقية", "رسوم منخفضة", "تحويلات سريعة"],
      },
      {
        id: "skrill",
        name: "حساب Skrill",
        title: "حساب Skrill",
        price: "$20",
        category: "محافظ رقمية",
        icon: "💰",
        iconImage: "/images/logos/skrill.png",
        popular: false,
        active: true,
        sort: 4,
        description: "محفظة Skrill الرقمية للمدفوعات الآمنة",
        features: ["مدفوعات آمنة", "تحويلات سريعة", "رسوم منخفضة"],
      },
      {
        id: "neteller",
        name: "حساب Neteller",
        title: "حساب Neteller",
        price: "$20",
        category: "محافظ رقمية",
        icon: "🏦",
        iconImage: "/images/logos/neteller.png",
        popular: false,
        active: true,
        sort: 5,
        description: "حساب Neteller مع بطاقة مصرفية",
        features: ["بطاقة مصرفية", "سحب نقدي", "مدفوعات آمنة"],
      },
      {
        id: "kast",
        name: "حساب Kast",
        title: "حساب Kast",
        price: "$20",
        category: "محافظ رقمية",
        icon: "kast",
        iconImage: "/images/logos/kast.png",
        popular: false,
        active: true,
        sort: 6,
        description: "محفظة Kast الرقمية المتطورة",
        features: ["تقنية متطورة", "أمان عالي", "واجهة سهلة"],
      },
      {
        id: "redotpay",
        name: "حساب Redotpay",
        title: "حساب Redotpay",
        price: "$20",
        category: "محافظ رقمية",
        icon: "redotpay",
        iconImage: "/images/logos/redotpay.png",
        popular: false,
        active: true,
        sort: 7,
        description: "محفظة Redotpay للمدفوعات الرقمية",
        features: ["مدفوعات رقمية", "تحويلات فورية", "أمان متقدم"],
      },
      {
        id: "okx",
        name: "حساب OKX",
        title: "حساب OKX",
        price: "$20",
        category: "منصات تداول",
        icon: "okx",
        iconImage: "/images/logos/okx.png",
        popular: false,
        active: true,
        sort: 8,
        description: "حساب OKX لتداول العملات الرقمية",
        features: ["تداول العملات الرقمية", "رسوم منخفضة", "أمان عالي"],
      },
      {
        id: "worldfirst",
        name: "حساب World First",
        title: "حساب World First",
        price: "$20",
        category: "تحويلات دولية",
        icon: "worldfirst",
        iconImage: "/images/logos/worldfirst.png",
        popular: false,
        active: true,
        sort: 9,
        description: "حساب World First للتحويلات الدولية",
        features: ["تحويلات دولية", "أسعار تنافسية", "خدمة احترافية"],
      },
      {
        id: "bybit",
        name: "حساب Bybit",
        title: "حساب Bybit",
        price: "$20",
        category: "منصات تداول",
        icon: "bybit",
        iconImage: "/images/logos/bybit.png",
        popular: false,
        active: true,
        sort: 10,
        description: "حساب Bybit لتداول العملات الرقمية",
        features: ["تداول متقدم", "رافعة مالية", "أدوات احترافية"],
      },
      {
        id: "bitget",
        name: "حساب Bitget",
        title: "حساب Bitget",
        price: "$20",
        category: "منصات تداول",
        icon: "bitget",
        iconImage: "/images/logos/bitget.png",
        popular: false,
        active: true,
        sort: 11,
        description: "حساب Bitget للتداول والاستثمار",
        features: ["تداول آمن", "استثمار ذكي", "واجهة سهلة"],
      },
      {
        id: "kucoin",
        name: "حساب KuCoin",
        title: "حساب KuCoin",
        price: "$20",
        category: "منصات تداول",
        icon: "kucoin",
        iconImage: "/images/logos/kucoin.png",
        popular: false,
        active: true,
        sort: 12,
        description: "حساب KuCoin لتداول العملات الرقمية",
        features: ["تنوع العملات", "رسوم منخفضة", "تداول متقدم"],
      },
      {
        id: "mexc",
        name: "حساب MEXC",
        title: "حساب MEXC",
        price: "$20",
        category: "منصات تداول",
        icon: "crypto",
        iconImage: "/images/logos/mexc.png",
        popular: false,
        active: true,
        sort: 13,
        description: "حساب MEXC لتداول العملات الرقمية",
        features: ["تداول متنوع", "سيولة عالية", "أمان متقدم"],
      },
      {
        id: "exness",
        name: "حساب Exness",
        title: "حساب Exness",
        price: "$20",
        category: "وسطاء فوركس",
        icon: "crypto",
        iconImage: "/images/logos/exness.png",
        popular: false,
        active: true,
        sort: 14,
        description: "حساب Exness لتداول الفوركس",
        features: ["تداول الفوركس", "رافعة مالية عالية", "تنفيذ سريع"],
      },
    ],
    payments: [
      { label: "فودافون كاش", value: "01062453344", icon: "📱", color: "red" },
      { label: "USDT TRC20", value: "TFUt8GRpk2R8Wv3FvoCiSUghRBQo4HrmQK", icon: "₿", color: "green" },
    ],
    features: [
      { title: "أمان عالي", desc: "حماية متقدمة لجميع المعاملات", icon: "shield" },
      { title: "دعم 24/7", desc: "فريق دعم متاح طوال الوقت", icon: "headphones" },
      { title: "سرعة في التنفيذ", desc: "تسليم الخدمات خلال ساعات", icon: "zap" },
      { title: "أسعار تنافسية", desc: "أفضل الأسعار في السوق", icon: "dollar-sign" },
    ],
    faq: [
      {
        question: "كم يستغرق تفعيل الحساب؟",
        answer: "عادة ما يتم تفعيل الحسابات خلال 24-48 ساعة من تأكيد الدفع.",
      },
      {
        question: "هل الحسابات آمنة؟",
        answer: "نعم، جميع الحسابات مفعلة بشكل قانوني وآمن مع ضمان كامل.",
      },
      {
        question: "ما هي طرق الدفع المتاحة؟",
        answer: "نقبل فودافون كاش والعملات الرقمية USDT TRC20.",
      },
      {
        question: "هل يمكنني استرداد المبلغ؟",
        answer: "نعم، نوفر ضمان استرداد كامل خلال 7 أيام في حالة عدم الرضا.",
      },
    ],
    contact: {
      title: "ابدأ رحلتك المالية اليوم",
      subtitle: "فريق الدعم متاح 24/7 للإجابة على استفساراتك",
      whatsapp: "تواصل عبر واتساب",
      features: ["رد فوري خلال دقائق", "استشارة مجانية", "ضمان الخدمة 100%"],
    },
    logos: [
      { name: "PayPal", src: "/images/logos/paypal.png" },
      { name: "Wise", src: "/images/logos/wise.png" },
      { name: "Skrill", src: "/images/logos/skrill.png" },
      { name: "Neteller", src: "/images/logos/neteller.png" },
      { name: "Payoneer", src: "/images/logos/payoneer.png" },
      { name: "OKX", src: "/images/logos/okx.png" },
      { name: "Bybit", src: "/images/logos/bybit.png" },
      { name: "Bitget", src: "/images/logos/bitget.png" },
      { name: "KuCoin", src: "/images/logos/kucoin.png" },
      { name: "Exness", src: "/images/logos/exness.png" },
      { name: "MEXC", src: "/images/logos/mexc.png" },
      { name: "Vodafone Cash", src: "/images/logos/vodafone-cash.png" },
    ],
    testimonials: [
      {
        name: "أحمد محمد",
        role: "رجل أعمال",
        quote: "خدمة ممتازة وسريعة، حصلت على حساب PayPal مفعل خلال يوم واحد",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "فاطمة علي",
        role: "مطورة ويب",
        quote: "أفضل موقع للحصول على الحسابات المصرفية الإلكترونية، أنصح به بشدة",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "محمود حسن",
        role: "مستقل",
        quote: "دعم فني ممتاز وأسعار معقولة، تعاملت معهم أكثر من مرة",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    cta: {
      title: "جاهز لبدء رحلتك المالية؟",
      subtitle: "انضم إلى آلاف العملاء الراضين",
      primaryText: "ابدأ الآن",
      secondaryText: "تواصل معنا",
    },
  },
  en: {
    site: {
      name: "KYCtrust",
      description: "Specialized service for electronic bank accounts and secure financial services",
      phone: "+20-106-245-3344",
      tagline: "Your trusted partner in the digital world",
      logoSrc: "/images/brand/novapay-logo.png",
    },
    hero: {
      title: "KYCtrust",
      subtitle: "Integrated platform for digital financial services",
      description: "Get the best electronic bank accounts and digital wallets with unmatched security and speed",
      cta: "Start Your Financial Journey",
      secondary: "Browse Our Services",
      stats: [
        { number: "1000+", label: "Happy Clients" },
        { number: "24/7", label: "Support" },
        { number: "99.9%", label: "Success Rate" },
        { number: "15+", label: "Services Available" },
      ],
    },
    services: [
      {
        id: "paypal",
        name: "PayPal Account",
        title: "PayPal Account",
        price: "$15",
        category: "Digital Wallets",
        icon: "💳",
        iconImage: "/images/logos/paypal.png",
        popular: true,
        active: true,
        sort: 1,
        description: "Fully activated PayPal account with send and receive capabilities",
        note: "Includes full activation",
        features: ["Full activation", "Send & receive", "Free support"],
      },
      {
        id: "payoneer",
        name: "Payoneer Account",
        title: "Payoneer Account",
        price: "$30",
        category: "Bank Accounts",
        icon: "💼",
        iconImage: "/images/logos/payoneer.png",
        popular: true,
        active: true,
        sort: 2,
        description: "Payoneer account with Mastercard",
        note: "Includes physical card",
        features: ["Mastercard included", "Global transfers", "ATM withdrawals"],
      },
      {
        id: "wise",
        name: "Wise Account",
        title: "Wise Account",
        price: "$30",
        category: "International Transfers",
        icon: "🌍",
        iconImage: "/images/logos/wise.png",
        popular: false,
        active: true,
        sort: 3,
        description: "Wise account for international transfers with lowest fees",
        note: "Best exchange rates",
        features: ["Real exchange rates", "Low fees", "Fast transfers"],
      },
      {
        id: "skrill",
        name: "Skrill Account",
        title: "Skrill Account",
        price: "$20",
        category: "Digital Wallets",
        icon: "💰",
        iconImage: "/images/logos/skrill.png",
        popular: false,
        active: true,
        sort: 4,
        description: "Skrill digital wallet for secure payments",
        features: ["Secure payments", "Fast transfers", "Low fees"],
      },
      {
        id: "neteller",
        name: "Neteller Account",
        title: "Neteller Account",
        price: "$20",
        category: "Digital Wallets",
        icon: "🏦",
        iconImage: "/images/logos/neteller.png",
        popular: false,
        active: true,
        sort: 5,
        description: "Neteller account with debit card",
        features: ["Debit card", "ATM access", "Secure payments"],
      },
      {
        id: "kast",
        name: "Kast Account",
        title: "Kast Account",
        price: "$20",
        category: "Digital Wallets",
        icon: "kast",
        iconImage: "/images/logos/kast.png",
        popular: false,
        active: true,
        sort: 6,
        description: "Advanced Kast digital wallet",
        features: ["Advanced technology", "High security", "Easy interface"],
      },
      {
        id: "redotpay",
        name: "Redotpay Account",
        title: "Redotpay Account",
        price: "$20",
        category: "Digital Wallets",
        icon: "redotpay",
        iconImage: "/images/logos/redotpay.png",
        popular: false,
        active: true,
        sort: 7,
        description: "Redotpay wallet for digital payments",
        features: ["Digital payments", "Instant transfers", "Advanced security"],
      },
      {
        id: "okx",
        name: "OKX Account",
        title: "OKX Account",
        price: "$20",
        category: "Trading Platforms",
        icon: "okx",
        iconImage: "/images/logos/okx.png",
        popular: false,
        active: true,
        sort: 8,
        description: "OKX account for cryptocurrency trading",
        features: ["Crypto trading", "Low fees", "High security"],
      },
      {
        id: "worldfirst",
        name: "World First Account",
        title: "World First Account",
        price: "$20",
        category: "International Transfers",
        icon: "worldfirst",
        iconImage: "/images/logos/worldfirst.png",
        popular: false,
        active: true,
        sort: 9,
        description: "World First account for international transfers",
        features: ["Global transfers", "Competitive rates", "Professional service"],
      },
      {
        id: "bybit",
        name: "Bybit Account",
        title: "Bybit Account",
        price: "$20",
        category: "Trading Platforms",
        icon: "bybit",
        iconImage: "/images/logos/bybit.png",
        popular: false,
        active: true,
        sort: 10,
        description: "Bybit account for cryptocurrency trading",
        features: ["Advanced trading", "Leverage", "Professional tools"],
      },
      {
        id: "bitget",
        name: "Bitget Account",
        title: "Bitget Account",
        price: "$20",
        category: "Trading Platforms",
        icon: "bitget",
        iconImage: "/images/logos/bitget.png",
        popular: false,
        active: true,
        sort: 11,
        description: "Bitget account for trading and investment",
        features: ["Safe trading", "Smart investment", "Easy interface"],
      },
      {
        id: "kucoin",
        name: "KuCoin Account",
        title: "KuCoin Account",
        price: "$20",
        category: "Trading Platforms",
        icon: "kucoin",
        iconImage: "/images/logos/kucoin.png",
        popular: false,
        active: true,
        sort: 12,
        description: "KuCoin account for cryptocurrency trading",
        features: ["Diverse coins", "Low fees", "Advanced trading"],
      },
      {
        id: "mexc",
        name: "MEXC Account",
        title: "MEXC Account",
        price: "$20",
        category: "Trading Platforms",
        icon: "crypto",
        iconImage: "/images/logos/mexc.png",
        popular: false,
        active: true,
        sort: 13,
        description: "MEXC account for cryptocurrency trading",
        features: ["Diverse trading", "High liquidity", "Advanced security"],
      },
      {
        id: "exness",
        name: "Exness Account",
        title: "Exness Account",
        price: "$20",
        category: "Forex Brokers",
        icon: "crypto",
        iconImage: "/images/logos/exness.png",
        popular: false,
        active: true,
        sort: 14,
        description: "Exness account for forex trading",
        features: ["Forex trading", "High leverage", "Fast execution"],
      },
    ],
    payments: [
      { label: "Vodafone Cash", value: "01062453344", icon: "📱", color: "red" },
      { label: "USDT TRC20", value: "TFUt8GRpk2R8Wv3FvoCiSUghRBQo4HrmQK", icon: "₿", color: "green" },
    ],
    features: [
      { title: "High Security", desc: "Advanced protection for all transactions", icon: "shield" },
      { title: "24/7 Support", desc: "Support team available around the clock", icon: "headphones" },
      { title: "Fast Execution", desc: "Service delivery within hours", icon: "zap" },
      { title: "Competitive Prices", desc: "Best prices in the market", icon: "dollar-sign" },
    ],
    faq: [
      {
        question: "How long does account activation take?",
        answer: "Accounts are usually activated within 24-48 hours of payment confirmation.",
      },
      {
        question: "Are the accounts secure?",
        answer: "Yes, all accounts are legally and securely activated with full guarantee.",
      },
      {
        question: "What payment methods are available?",
        answer: "We accept Vodafone Cash and USDT TRC20 cryptocurrency.",
      },
      {
        question: "Can I get a refund?",
        answer: "Yes, we provide full refund guarantee within 7 days if not satisfied.",
      },
    ],
    contact: {
      title: "Start Your Financial Journey Today",
      subtitle: "Support team available 24/7 to answer your questions",
      whatsapp: "Contact via WhatsApp",
      features: ["Instant reply within minutes", "Free consultation", "100% service guarantee"],
    },
    logos: [
      { name: "PayPal", src: "/images/logos/paypal.png" },
      { name: "Wise", src: "/images/logos/wise.png" },
      { name: "Skrill", src: "/images/logos/skrill.png" },
      { name: "Neteller", src: "/images/logos/neteller.png" },
      { name: "Payoneer", src: "/images/logos/payoneer.png" },
      { name: "OKX", src: "/images/logos/okx.png" },
      { name: "Bybit", src: "/images/logos/bybit.png" },
      { name: "Bitget", src: "/images/logos/bitget.png" },
      { name: "KuCoin", src: "/images/logos/kucoin.png" },
      { name: "Exness", src: "/images/logos/exness.png" },
      { name: "MEXC", src: "/images/logos/mexc.png" },
      { name: "Vodafone Cash", src: "/images/logos/vodafone-cash.png" },
    ],
    testimonials: [
      {
        name: "Ahmed Mohamed",
        role: "Business Owner",
        quote: "Excellent and fast service, got my PayPal account activated within one day",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Fatima Ali",
        role: "Web Developer",
        quote: "Best website for electronic bank accounts, highly recommend it",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Mahmoud Hassan",
        role: "Freelancer",
        quote: "Excellent technical support and reasonable prices, dealt with them multiple times",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    cta: {
      title: "Ready to Start Your Financial Journey?",
      subtitle: "Join thousands of satisfied customers",
      primaryText: "Get Started",
      secondaryText: "Contact Us",
    },
  },
}

export const defaultState: CMSState = {
  locale: "ar",
  blocks: [
    { id: "hero", type: "hero", enabled: true },
    { id: "logos", type: "logos", enabled: true },
    { id: "features", type: "features", enabled: true },
    { id: "services", type: "services", enabled: true },
    { id: "payments", type: "payments", enabled: true },
    { id: "testimonials", type: "testimonials", enabled: true },
    { id: "faq", type: "faq", enabled: true },
    { id: "contact", type: "contact", enabled: true },
    { id: "cta", type: "cta", enabled: false },
  ],
  content: defaultContent,
  design: {
    theme: "system",
    palette: "violet-emerald",
    anim: {
      enableReveal: true,
      intensity: 1,
      parallax: 14,
    },
  },
}
